export type LicenseCategory = {
  id: string;
  label: string;
  icon: string;
  items: string[];
};

export const LICENSE_CATEGORIES: LicenseCategory[] = [
  {
    id: "fuehrerschein-pkw",
    label: "Führerschein – Pkw & Motorrad",
    icon: "🚗",
    items: [
      "AM – Moped bis 45 km/h",
      "A1 – Leichtkraftrad",
      "A2 – Motorrad bis 35 kW",
      "A – Kraftrad (unbeschränkt)",
      "B – Pkw",
      "B – Pkw (nur Automatik)",
      "BE – Pkw mit Anhänger",
      "B96 – Pkw mit Anhänger (bis 4.250 kg)",
      "M – Moped",
      "S – Klein-Kraftfahrzeug (< 45 km/h, < 50 ccm)",
      "Mofa-Prüfbescheinigung",
      "DMSB Nationale Lizenz A (Motorsport)",
    ],
  },
  {
    id: "fuehrerschein-schwer",
    label: "Führerschein – LKW, Bus & Schwertransport",
    icon: "🚛",
    items: [
      "C – LKW über 3,5 t (Anhänger bis 750 kg)",
      "C1 – LKW bis 7,5 t (Anhänger bis 750 kg)",
      "C1E – LKW bis 7,5 t mit Anhänger",
      "CE – LKW mit Anhänger (über 750 kg)",
      "CE 79 – Lastzüge",
      "D – Bus (Omnibus)",
      "D1 – Kleinbus bis 16 Personen",
      "DE – Bus mit Anhänger",
      "L – Zug-/Arbeitsmaschinen (bis 40 km/h)",
      "T – Traktor/Arbeitsmaschinen",
      "Personenbeförderungsschein",
      "Schlüsselzahl 95 im Führerschein (Berufskraftfahrer)",
      "Fahrerkarte (D) – Digitaler Fahrtenschreiber",
      "Triebfahrzeugführerschein Klasse 3",
    ],
  },
  {
    id: "drohnen",
    label: "Drohnen",
    icon: "🚁",
    items: [
      "EU Kompetenznachweis A1/A3 für Drohnenpiloten",
      "EU Kompetenznachweis A2 für Drohnenpiloten",
      "Drohnenflug-Zertifikat bis 2 kg – Deutsche LuftVO",
      "Kenntnisnachweis nach §21d (Drohnen über 2 kg) – dt. LuftVO",
      "CAA Commercial Remote Pilot License [UK]",
      "CATT – French Remote Pilot Certificate A1/A2/A3 [FR]",
      "FAA Commercial Remote Pilot License [US]",
    ],
  },
  {
    id: "luftfahrt",
    label: "Luftfahrt & Fallschirm",
    icon: "✈️",
    items: [
      "Privatpilotenlizenz PPL-A (Motorflugzeug)",
      "Commercial Pilot Licence CPL-A (Flugzeug)",
      "Segelfluglizenz (GPL Glider Pilot License)",
      "Ultraleichtfluglizenz SPL",
      "Fallschirmspringer Lizenz",
      "Gleitschirm A-Lizenz",
      "Gleitschirm B-Lizenz",
      "Gleitschirm Höhenflugausweis",
      "Gleitschirm Lernausweis",
      "Hängegleiter A-Lizenz",
      "Hängegleiter B-Lizenz",
      "KSA Kite Sport Licence",
      "Offshore Lizenz (Windpark/Bohrinsel)",
      "Zuverlässigkeitsüberprüfung nach §7 Luftsicherheitsgesetz",
    ],
  },
  {
    id: "wasserfahrzeuge",
    label: "Wasserfahrzeuge & Schifffahrt",
    icon: "⛵",
    items: [
      "Sportbootführerschein Binnen (SBF)",
      "Sportbootführerschein Binnen unter Segel (SBF)",
      "Sportbootführerschein See (SBF)",
      "Sporthochseeschifferschein (SHS) – nur Motor",
      "Sporthochseeschifferschein unter Segel (SHS)",
      "Sportküstenschifferschein – nur Motor (bis 12 SM)",
      "Sportküstenschifferschein unter Segel (bis 12 SM)",
      "Sportseeschifferschein – nur Motor (SSS, bis 30 SM)",
      "Sportseeschifferschein unter Segel (SSS, bis 30 SM)",
      "Bodenseeschifferpatent (BSP)",
      "RYA Yachtmaster Offshore",
      "Segelsurf Grundschein",
      "UBI – UKW-Sprechfunkzeugnis Binnenschifffahrtsfunk",
      "Befähigungsnachweis BSH Sicherheitsgrundausbildung Seeleute",
    ],
  },
  {
    id: "tauchen-padi",
    label: "Tauchen – PADI",
    icon: "🤿",
    items: [
      "Tauchschein – PADI Open Water Diver",
      "Tauchschein – PADI Advanced Open Water Diver",
      "Tauchschein – PADI Rescue Diver",
      "Tauchschein – PADI Divemaster",
      "Tauchschein – PADI Assistant Instructor",
      "Tauchschein – PADI Open Water Scuba Instructor",
      "Tauchschein – PADI Master Scuba Diver Trainer",
      "Tauchschein – PADI Course Director",
      "Tauchschein – PADI Master Instructor",
      "Tauchschein – PADI Freediver",
      "Tauchschein – PADI Advanced Freediver",
      "Tauchschein – PADI Master Freediver",
      "Tauchschein – PADI Freediver Instructor",
      "Tauchschein – PADI Advanced Freediver Instructor",
    ],
  },
  {
    id: "tauchen-sonstige",
    label: "Tauchen – CMAS, SSI & Sonstige",
    icon: "🐟",
    items: [
      "Tauchschein – CMAS*",
      "Tauchschein – CMAS**",
      "Tauchschein – CMAS***",
      "Tauchschein – CMAS****",
      "Tauchschein – CMAS TL**",
      "Tauchschein – CMAS TL****",
      "Tauchschein – DTSA Nitrox* / VDST-CMAS Basic Nitrox Diver",
      "Tauchschein – SSI Open Water Diver",
      "Tauchschein – SSI Advanced Open Water Instructor",
      "Tauchschein – SSI Open Water Instructor",
      "Tauchschein – SSI Dive Master",
      "Tauchschein – SSI Freediving Level 1",
      "Tauchschein – SSI Freediving Level 2",
      "Tauchschein – SSI Freediving Level 3",
      "Tauchschein – SSI React Right Oxygen Provider",
      "Tauchschein – NAUI Scuba Diver",
      "Tauchschein – IAC Freediver **",
      "Tauchschein – IAC Freediver ***",
      "Tauchschein – IAC Freediver ****",
      "Tauchschein – Deep Diver Brevet International",
      "DRSA – Deutsches Rettungsschwimmerabzeichen",
    ],
  },
  {
    id: "hebebuehnen",
    label: "Hebebühnen, Stapler & Maschinen",
    icon: "🏗️",
    items: [
      "Fahrausweis für Flurförderfahrzeuge (Gabelstapler)",
      "Bediener Flurförderfahrzeug variabler Reichweite (DGUV 308-008 2a)",
      "Bediener von Hubarbeitsbühnen (DGUV Grundsatz 308-008)",
      "Teleskopstaplerschein (Befähigungsnachweis DGUV 308-009)",
      "IPAF Lizenz Mobil Boom (3b) – Gelenk-/Teleskoparbeitsbühnen",
      "IPAF Lizenz Mobil Vertikal (3a) – Scherenarbeitsbühnen",
      "IPAF Lizenz Statisch Boom (1b)",
      "IPAF Lizenz Statisch Vertikal (1a) – Senkrecht-Personenlifte",
    ],
  },
  {
    id: "elektro-veranstaltung",
    label: "Elektro & Veranstaltungstechnik",
    icon: "⚡",
    items: [
      "Elektrofachkraft für festgelegte Tätigkeiten",
      "Elektrofachkraft für Veranstaltungstechnik (SQQ1)",
      "Elektrotechnisch unterwiesene Person (EuP) (DIN VDE 0105-100)",
      "SQP4 – Mobile elektrische Anlagen in der Veranstaltungstechnik",
      "Geprüfter Meister/in für Veranstaltungstechnik",
      "Bühnenmeister (Kollektivvertrag österr. Theater)",
    ],
  },
  {
    id: "film-kamera",
    label: "Film- & Kameratechnik",
    icon: "🎬",
    items: [
      "Befähigungsnachweis – Kamerakran handgetrieben (BG ETEM/VBG, BGI 814)",
      "Befähigungsnachweis – Kamerakran Teleskop (BG ETEM/VBG, BGI 814)",
      "Befähigungsnachweis – Ferngest. Kamerasystem auf Schienen (BG ETEM/VBG)",
      "Befähigungsnachweis – Ferngest. Kamerasystem auf Seilen (BG ETEM/VBG)",
      "AI Cine Creator",
      "ZDF Selbstfahrgenehmigung für freie Mitarbeiter",
    ],
  },
  {
    id: "arbeitssicherheit",
    label: "Arbeitssicherheit & Höhenarbeit",
    icon: "🦺",
    items: [
      "RSA 21 – Sicherung von Arbeitsstellen an Straßen",
      "SZT – Seilzugangstechnik Level 1",
      "SZT – Seilzugangstechnik Level 2",
      "SZT – Seilzugangstechnik Level 3",
      "SKT A – Seilklettertechnik Stufe A",
      "IRATA Level 1",
      "Sachkundige/r für PSA gegen Absturz (BGG 906)",
      "Sachkundige/r für Anschlagmittel",
      "Sachkundige/r für Traversensysteme",
      "Sachkunde Veranstaltungsrigging SQ Q2 – Level 1",
      "Sachkunde Veranstaltungsrigging SQ Q2 – Level 2",
      "Sachkunde Veranstaltungsrigging SQ Q2 – Level 3",
      "G26.3 – Atemschutztauglichkeit",
      "Brandschutz- und Evakuierungshelfer/in nach DGUV 205-023",
      "SB1 – Grundseminar für Sicherheitsbeauftragte",
      "Planungskoordinator/in für Veranstaltungssicherheit (TÜV)",
      "Bergretter",
      "Arbeitssicherheit Baum I",
      "Basis-Qualifikation Schutz und Sicherheit §34a GewO",
    ],
  },
  {
    id: "funk",
    label: "Funk & Kommunikation",
    icon: "📡",
    items: [
      "Allgemeines Sprechfunkzeugnis AZF",
      "Beschränkt gültiges Sprechfunkzeugnis BZF I",
      "Beschränkt gültiges Sprechfunkzeugnis BZF II",
      "BOS-Sprechfunkzeugnis",
      "SRC – Short Range Certificate (Funklizenz)",
      "Amateurfunkzeugnis Klasse A",
      "Amateurfunkzeugnis Klasse E",
    ],
  },
  {
    id: "waffen-sprengstoff",
    label: "Waffen & Sprengstoff",
    icon: "🔫",
    items: [
      "Kleiner Waffenschein",
      "Waffenschein",
      "WBK – Waffenbesitzkarte [AT]",
      "Waffensachkunde nach §7 WaffG für Berufswaffenträger",
      "Waffensachkunde nach §7 WaffG für Sportschützen",
      "Ausnahmegenehmigung Erwerb/Umgang verbotener Waffen nach §40 WaffG",
      "Erlaubnis nach §7 Sprengstoffgesetz",
      "Befähigungsschein nach §20 Sprengstoffgesetz",
      "Jagdschein",
    ],
  },
  {
    id: "rettung-medizin",
    label: "Rettung & Medizin",
    icon: "🚑",
    items: [
      "Ersthelfer/in nach DGUV 304-001",
      "Rettungssanitäter",
      "DRSA – Deutsches Rettungsschwimmerabzeichen",
    ],
  },
  {
    id: "sport-instruktoren",
    label: "Sport & Instruktoren",
    icon: "🎿",
    items: [
      "DSLV Skilehrer/in Level 1",
      "DSLV Snowboardlehrer/in Level 1",
      "DSV Skilehrer/in",
      "DSV Snowboardlehrer/in",
      "DSV Instructor",
      "DSV Segeltrainer-C Breitensport",
      "DAV Trainer C Sportklettern",
      "Fitnesstrainer/in B-Lizenz",
      "Grouptrainer/in B-Lizenz (Fitness)",
      "Yogalehrer/in (RYS-200)",
      "Fischereischein (Angelschein)",
      "Segelsurf Grundschein",
      "Reitabzeichen RA2 (Silbernes Reitabzeichen)",
      "Reitabzeichen RA3",
      "Reitabzeichen RA4 (Bronzenes Reitabzeichen)",
      "Reitabzeichen RA5 (Kleines Reitabzeichen)",
      "Goldenes Reitabzeichen",
    ],
  },
  {
    id: "set-safety",
    label: "Set Safety & Film-Zertifikate",
    icon: "🛡️",
    items: [
      "Safe on Set – Hygienecoaching Webinar",
      "Safe Sets COVID-19 Level A",
      "Hygienebeauftragter Film/Fernseh-/Fotoproduktionen (DEKRA)",
      "Green Consultant Film & TV (IHK-Zertifikat)",
      "Production Safety Accredited (PSA3)",
      "Vertrauensperson Film + Kultur",
      "AdA-Schein (nach AEVO)",
    ],
  },
  {
    id: "presse-sonstiges",
    label: "Presse, Akkreditierung & Sonstiges",
    icon: "📰",
    items: [
      "Presseausweis (Deutschland)",
      "Internationaler Presseausweis",
      "Media (I) Visa – Journalistenvisum USA",
      "Greencard USA",
      "Sensibilisation VHSS [FR]",
      "Formation référent·e VHSS [FR]",
      "Formation certifiante écoproduction – CCP [FR]",
      "Formation courte écoproduction – CAT [FR]",
    ],
  },
];

export const ALL_LICENSES: { category: string; label: string }[] = LICENSE_CATEGORIES.flatMap(
  (cat) => cat.items.map((item) => ({ category: cat.label, label: item }))
);
